# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a currupted csv file!

## Objectives
You will be able to:
* Import data from csv files and Excel files
* Understand and explain key arguments for imports
* Save information to csv and Excel files
* Access data within a Pandas DataFrame (print() and .head())

#  Loading Files with Summary or Meta Data

Load either of the files Zipcode_Demos.csv or Zipcode_Demos.xlsx. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled 'Data'.

In [23]:
import numpy as np
import pandas as pd

zips = pd.read_csv('Data/Zipcode_Demos.csv',skiprows=[1],nrows=45,usecols=[0,1,2])

In [24]:
zips

     0                   Average Statistics  Unnamed: 2
0    2                    JURISDICTION NAME   10005.800
1    3                   COUNT PARTICIPANTS       9.400
2    4                         COUNT FEMALE       4.800
3    5                       PERCENT FEMALE       0.404
4    6                           COUNT MALE       4.600
5    7                         PERCENT MALE       0.396
6    8                 COUNT GENDER UNKNOWN       0.000
7    9               PERCENT GENDER UNKNOWN       0.000
8   10                   COUNT GENDER TOTAL       9.400
9   11                 PERCENT GENDER TOTAL      80.000
10  12               COUNT PACIFIC ISLANDER       0.000
11  13             PERCENT PACIFIC ISLANDER       0.000
12  14                COUNT HISPANIC LATINO       2.000
13  15              PERCENT HISPANIC LATINO       0.105
14  16                COUNT AMERICAN INDIAN       0.000
15  17              PERCENT AMERICAN INDIAN       0.000
16  18             COUNT ASIAN NON HISPANIC       3.600
17  19           PERCENT ASIAN NON HISPANIC       0.437
18  20             COUNT WHITE NON HISPANIC       0.800
19  21           PERCENT WHITE NON HISPANIC       0.036
20  22             COUNT BLACK NON HISPANIC       2.600
21  23           PERCENT BLACK NON HISPANIC       0.181
22  24                COUNT OTHER ETHNICITY       0.400
23  25              PERCENT OTHER ETHNICITY       0.040
24  26              COUNT ETHNICITY UNKNOWN       0.000
25  27            PERCENT ETHNICITY UNKNOWN       0.000
26  28                COUNT ETHNICITY TOTAL       9.400
27  29              PERCENT ETHNICITY TOTAL      79.900
28  30       COUNT PERMANENT RESIDENT ALIEN       0.500
29  31     PERCENT PERMANENT RESIDENT ALIEN       0.061
30  32                     COUNT US CITIZEN       8.900
31  33                   PERCENT US CITIZEN       0.739
32  34           COUNT OTHER CITIZEN STATUS       0.000
33  35         PERCENT OTHER CITIZEN STATUS       0.000
34  36         COUNT CITIZEN STATUS UNKNOWN       0.000
35  37       PERCENT CITIZEN STATUS UNKNOWN       0.000
36  38           COUNT CITIZEN STATUS TOTAL       9.400
37  39         PERCENT CITIZEN STATUS TOTAL      80.000
38  40     COUNT RECEIVES PUBLIC ASSISTANCE       2.300
39  41   PERCENT RECEIVES PUBLIC ASSISTANCE       0.151
40  42    COUNT NRECEIVES PUBLIC ASSISTANCE       7.100
41  43  PERCENT NRECEIVES PUBLIC ASSISTANCE       0.649
42  44      COUNT PUBLIC ASSISTANCE UNKNOWN       0.000
43  45    PERCENT PUBLIC ASSISTANCE UNKNOWN       0.000
44  46        COUNT PUBLIC ASSISTANCE TOTAL       9.400

## Level Up (Optional)

### Loading Corrupt CSV files

Occassionally, you encountered some really ill formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is suppossed to use quotes to differentiate between the commas denoting fields and commas within those fields themselves. For example, we could have a table like this:  

ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restuarant was pretty good, we had a great time.,98765

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restuarant was pretty good, we had a great time.","98765"

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled Yelp_Reviews_corrupt.csv. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [8]:
#Hint: here's a useful programming pattern to use.
try:
    corrupted = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv')
except Exception as e:
    print("There's something wrong with the file")

There's something wrong with the file

In [59]:
# #Your code here
# def read_file_csv(file):
    
corrupted = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv',nrows=1960)
corrupted_2 = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', skiprows= 1961, nrows=10)

In [62]:
corrupted
corrupted_2
#if we look into lines after the corrupted one, the column values are off

,,,,,,,STAY AWAY FROM THIS PLACE!!!!!!,5,sDofYImMQQmu4Le5G9zmpQ
3948,GAKFx4jFUtTOTpp_jDJnuA,0,2017-09-01,0.0,OUZWMw7EgO7D596pUelSlA,5.0,Nice relaxing atmosphere. Friendly service and...,1.0,6vJY67yve43Ijvn8RKVUow
3949,0QzCeORfF8EY34UODWRV9A,0,2017-09-03,0.0,7lbykaWFD8YBwT0mU1Rexw,4.0,Very pleased with our experience. Great off th...,0.0,6vJY67yve43Ijvn8RKVUow
3950,tlt8zNrZ6_A3DmXiM-cnBA,0,2016-06-12,0.0,Nd_soHwCYi8adcNIT2w9LQ,1.0,Wife went to this location and was horrible. N...,0.0,S0dnPb1OzaqdBSOxyLr7BQ
3952,XD0LjNuPPwJPsTAHecUh7A,0,2015-08-23,0.0,FUUTAr5CECrkfRa9Y2-MSg,1.0,Not baby friendly anymore.,NaN,NaN
Refused service for having an urban sized stroller due to fire hazards when the restaurant at 2:30 pm was almost empty.,0,RsgRH4ixaiJ1zWnmXam6pQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3953,J64Yg3hQJXSI-ipnfJUkiw,0,2016-08-24,0.0,WyXXGm0ryKoAlLi68pq-kg,2.0,Paid for an Escalade but got picked up by an o...,4.0,RsgRH4ixaiJ1zWnmXam6pQ
3956,JJDxLSeHkEFPUrPCxEFp0w,0,2015-11-12,0.0,jSVDzcNUKrd3HpF8xGxScA,2.0,If you don't mind the mechanic's attitude prob...,1.0,RsgRH4ixaiJ1zWnmXam6pQ
3957,3k9treY8PmsZ42bKmuICgA,0,2015-10-11,0.0,OT7KEec2NRlCc8mGMZOf6A,2.0,Not sure why this place gets 4*... Food is meh...,1.0,RsgRH4ixaiJ1zWnmXam6pQ
3959,JJys4pp5xmf3bB4E3lmxRA,0,2015-11-07,0.0,3ARL8Y4ZPZ1qE9vEk2PH6w,1.0,It was decent before now it's terrible. Wings ...,1.0,RsgRH4ixaiJ1zWnmXam6pQ
3966,wrcfLni9nmJK46Wb4XMkaQ,0,2016-06-09,0.0,Bi6sJcqCyi3sJj2hyYMCIQ,5.0,This location is awesome. Juan & Lily work har...,0.0,peAIvDTWt8K5Ie06LKwI-Q